version: "3"
services:
  # Event Service ========================================
  event:
    build:
      context: ./event_crud
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    # depends_on:
    #   - mongodb
    # environment:
    #   - FLASK_APP=events.py
    #   - FLASK_ENV=development
    # volumes:
    #   - .:/app
  # Notification Service =================================
  # notification:
  #   build:
  #     context: ./notification
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5001:5001
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     - FLASK_APP=notification.py
  #     - FLASK_ENV=development
  # volumes:
  #   - .:/app

  # Event Orcha Service ===================================
  # event-orcha:
  #   build:
  #     context: ./event_orcha
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5000:5000

  # MongoDB =============================================
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
  # MySQL ===============================================
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: veryS3ecureP@ssword
      MYSQL_DATABASE: ticketboost
      MYSQL_USER: ticketboost
      MYSQL_PASSWORD: veryS3ecureP@ssword
  # RabbitMQ ============================================
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ticketboost
      RABBITMQ_DEFAULT_PASS: veryS3ecureP@ssword

volumes:
  mongodb-data:
