_format_version: "2.1"
services:
  - name: frontend
    url: http://frontend:80
    routes:
      - name: frontend-route
        paths:
          - "/"

  - name: 3p-gateway
    url: http://3p-gateway:8100
    routes:
      - name: 3p-gateway-route
        paths:
          - "/3p-gateway"

  - name: billing
    url: http://billing:8002
    routes:
      - name: billing-route
        paths:
          - "/billing"

# http://localhost:8000/events/ - to connect via kong
# if a paths "/events" - # http://localhost:8000/events/events/ - to connect via kong
  - name: event
    url: http://event_crud:8004
    routes:
      - name: event-route
        paths:
          - "/"

  - name: event_orcha
    url: http://event_orcha:8005
    routes:
      - name: event-orcha-route
        paths:
          - "/eventstrator"

  - name: logging
    url: http://logging:8006
    routes:
      - name: logging-route
        paths:
          - "/logging"

  - name: merch_crud
    url: http://merch_crud:8007
    routes:
      - name: merch_crud-route
        paths:
          - "/merch"

  - name: merchcart_orcha
    url: http://merchcart_orcha:8008
    routes:
      - name: merchcart_orcha-route
        paths:
          - "/merchcart"

  - name: merchcheckout_orcha
    url: http://merchcheckout_orcha:8009
    routes:
      - name: merchcheckout_orcha-route
        paths:
          - "/merchcheckout"

  - name: notification
    url: http://notification:8010
    routes:
      - name: notification-route
        paths:
          - "/notification"

  - name: queue
    url: http://queue:8011
    routes:
      - name: queue-route
        paths:
          - "/queue"

  - name: rfid
    url: http://rfid:8012
    routes:
      - name: rfid-route
        paths:
          - "/rfid"

  - name: rfid_link
    url: http://rfid_link:8013
    routes:
      - name: rfid_link-route
        paths:
          - "/rfidlink"

  - name: seat
    url: http://seat:8014
    routes:
      - name: seat-route
        paths:
          - "/seat"

  - name: user
    url: http://user:8015
    routes:
      - name: view-all-user-tickets-route # route for view all tickets bought by user
        paths:
          - "/api/v1/user/<int:id>/tickets"
      - name: view-tickets-by-serial-route # route for view specific ticket bought by user by serial number
        paths:
          - "/api/v1/user/<int:id>/tickets/<int:serial_no>"
      - name: view-tickets-by-match-route # route for view all specific tickets bought by user by match id
        paths:
          - "/api/v1/user/<int:id>/tickets/match/<int:match_id>"
      - name: add-ticket-to-user-route # route for adding a ticket to user
        paths:
          - "/api/v1/user/<int:id>/tickets"
      - name: delete-ticket-from-user-route # route for deleting a ticket from user
        paths:
          - "/api/v1/user/<int:id>/tickets/<int:serial_no>"

  - name: venue
    url: http://venue:8016
    routes:
      - name: venue-route
        paths:
          - "/venue"

  - name: wallet
    url: http://wallet:8017
    routes:
      - name: wallet-route
        paths:
          - "/wallet"

plugins:
  - name: cors
    config:
      origins:
        - "*"
