_format_version: "2.1"

services:
  # There is no need for the frontend to be here
  # - name: frontend
  #   url: http://frontend:443
  #   routes:
  #     - name: frontend-route
  #       paths:
  #         - "/"

  # - name: match
  #   url: http://match:9001
  #   routes:
  #     - name: match-route
  #       paths:
  #         - "/api/v1/match"
  - name: match
    url: http://match:9001/graphql
    routes:
      - name: match-graphql-route
        paths:
          - "/api/v1/match"

  - name: queue
    url: ws://queue:9002/ws
    routes:
      - name: queue-route
        paths:
          - "/api/v1/queue"
        protocols:
          - ws
          - wss

  - name: billing
    url: http://billing:9003
    routes:
      - name: billing-route # route for billing
        paths:
          - "/api/v1/billing"

  - name: seat
    url: http://seat:9009
    routes:
      - name: seat-route
        paths:
          - "/api/v1/seat"

  - name: user
    url: http://user:9004
    routes:
      - name: user-route
        paths:
          - "/api/v1/user"

  - name: videoasset
    url: http://videoasset:9005
    routes:
      - name: videoasset-route
        paths:
          - "/api/v1/videoasset"

  - name: livestats
    url: http://livestats:9006
    routes:
      - name: livestats-route
        paths:
          - "/api/v1/livestats"

  - name: notification
    url: http://notification:9007
    routes:
      - name: notification-route
        paths:
          - "/api/v1/notification"

  - name: logging
    url: http://logging:9008
    routes:
      - name: logging-route
        paths:
          - "/api/v1/logging"
  
  - name: auth
    url: http://auth:9010
    routes:
      - name: auth-route
        paths:
          - "/api/v1/auth"

  - name: match-booking-orchestrator
    url: http://match-booking-orchestrator:9101
    routes:
      - name: match-booking-orchestrator-route
        paths:
          - "/api/v1/booking"

  - name: match-streaming-orchestrator
    url: http://match-streaming-orchestrator:9102
    routes:
      - name: match-streaming-orchestrator-route
        paths:
          - "/api/v1/streaming"

  - name: refund-orchestrator
    url: http://refund-orchestrator:9103
    routes:
      - name: refund-orchestrator-route
        paths:
          - "/api/v1/refund"

  - name: prometheus
    url: http://prometheus:9090
    routes:
      - name: prometheus
        paths:
          - /prom-metrics

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
  - name: prometheus
    config:
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      per_consumer: true
      # prefix: kong_api_
      upstream_health_metrics: true

  # - name: prometheus
  #   config:
  #     enable_exporting: true
  #     metrics_path: /metrics
  #     listen_address: 0.0.0.0:9100
