_format_version: "2.1"

services:
  # There is no need for the frontend to be here
  # - name: frontend
  #   url: http://frontend:443
  #   routes:
  #     - name: frontend-route
  #       paths:
  #         - "/"

  - name: match
    url: http://match:9001
    routes:
      - name: match-route
        paths:
          - "/match"

  - name: queue
    url: http://queue:9002
    routes:
      - name: queue-route
        paths:
          - "/queue"

  - name: billing
    url: http://billing:9003
    routes:
      - name: billing-route
        paths:
          - "/billing"

  - name: seat
    url: http://seat:9009
    routes:
      - name: seat-route
        paths:
          - "/seat"

  - name: user
    url: http://user:9004
    routes:
      - name: view-all-user-tickets-route # route for view all tickets bought by user
        paths:
          - "/api/v1/user/<int:id>/tickets"
      - name: view-tickets-by-serial-route # route for view specific ticket bought by user by serial number
        paths:
          - "/api/v1/user/<int:id>/tickets/<int:serial_no>"
      - name: view-tickets-by-match-route # route for view all specific tickets bought by user by match id
        paths:
          - "/api/v1/user/<int:id>/tickets/match/<int:match_id>"
      - name: add-ticket-to-user-route # route for adding a ticket to user
        paths:
          - "/api/v1/user/<int:id>/tickets"
      - name: delete-ticket-from-user-route # route for deleting a ticket from user
        paths:
          - "/api/v1/user/<int:id>/tickets/<int:serial_no>"

  - name: videoasset
    url: http://videoasset:9005
    routes:
      - name: videoasset-route
        paths:
          - "/videoasset"

  - name: livematch
    url: http://livematch:9006
    routes:
      - name: livematch-route
        paths:
          - "/livematch"

  - name: notification
    url: http://notification:9007
    routes:
      - name: notification-route
        paths:
          - "/notification"

  - name: logging
    url: http://logging:9008
    routes:
      - name: logging-route
        paths:
          - "/logging"

  - name: match-booking-orchestrator
    url: http://match-booking-orchestrator:9101
    routes:
      - name: match-booking-orchestrator-route
        paths:
          - "/match-booking"

  - name: match-streaming-orchestrator
    url: http://match-streaming-orchestrator:9102
    routes:
      - name: match-streaming-orchestrator-route
        paths:
          - "/match-streaming"

  - name: refund-orchestrator
    url: http://refund-orchestrator:9103
    routes:
      - name: refund-orchestrator-route
        paths:
          - "/refund"

plugins:
  - name: cors
    config:
      origins:
        - "*"
