_format_version: "2.1"

services:
  # There is no need for the frontend to be here
  # - name: frontend
  #   url: http://frontend:443
  #   routes:
  #     - name: frontend-route
  #       paths:
  #         - "/"

  - name: match
    url: http://match:9001
    routes:
      - name: match-route
        paths:
          - "/match"

  - name: queue
    url: http://queue:9002
    routes:
      - name: queue-route
        paths:
          - "/queue"

  - name: billing
    url: http://billing:9003
    routes:
      - name: billing-route
        paths:
          - "/billing"

  - name: seat
    url: http://seat:9009
    routes:
      - name: seat-route
        paths:
          - "/seat"

  - name: user
    url: http://user:9004
    routes:
      - name: user-route
        paths:
          - "/user"
      - name: create-account-route
        paths:
          - "/api/v1/createAccount"
      - name: login-route
        paths:
          - "/api/v1/login"
      - name: view-user-tickets-route
        paths:
          - "/api/v1/user/:user_id/tickets"
      - name: view-ticket-route
        paths:
          - "/api/v1/user/:user_id/tickets/:ticket_id"
      - name: add-ticket-route
        paths:
          - "/api/v1/user/:user_id/tickets/add"

  - name: videoasset
    url: http://videoasset:9005
    routes:
      - name: videoasset-route
        paths:
          - "/videoasset"

  - name: livematch
    url: http://livematch:9006
    routes:
      - name: livematch-route
        paths:
          - "/livematch"

  - name: notification
    url: http://notification:9007
    routes:
      - name: notification-route
        paths:
          - "/notification"

  - name: logging
    url: http://logging:9008
    routes:
      - name: logging-route
        paths:
          - "/logging"

  - name: match-booking-orchestrator
    url: http://match-booking-orchestrator:9101
    routes:
      - name: match-booking-orchestrator-route
        paths:
          - "/match-booking"

  - name: match-streaming-orchestrator
    url: http://match-streaming-orchestrator:9102
    routes:
      - name: match-streaming-orchestrator-route
        paths:
          - "/match-streaming"

  - name: refund-orchestrator
    url: http://refund-orchestrator:9103
    routes:
      - name: refund-orchestrator-route
        paths:
          - "/refund"

plugins:
  - name: cors
    config:
      origins:
        - "*"
