apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: queue
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: queue
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/kong-net: "true"
        io.kompose.service: queue
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: AKIAWN2YBRQXNT2OH6IZ
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
          image: queue
          name: queue
      restartPolicy: Always
