apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: videoasset
  name: videoasset
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: videoasset
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/kong-net: "true"
        io.kompose.service: videoasset
    spec:
      containers:
        - image: videoasset
          name: videoasset
      restartPolicy: Always
